# Generated by Django 4.1.3 on 2022-12-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jruser",
            old_name="baseUrl",
            new_name="base_url",
        ),
    ]
