# Generated by Django 4.1.3 on 2022-12-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jira", "0002_rename_baseurl_jruser_base_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="jrtask",
            name="date_time",
            field=models.DateTimeField(null=True, verbose_name="DateTime"),
        ),
        migrations.AddField(
            model_name="jrtask",
            name="label",
            field=models.CharField(max_length=50, null=True, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="jrtask",
            name="text",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="Text"
            ),
        ),
    ]
