# Generated by Django 4.1.3 on 2022-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgchat',
            name='chat_type',
            field=models.CharField(choices=[('Group', 'Group'), ('Channel', 'Channel')], default='Channel', max_length=10, null=True, verbose_name='Chat Type'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='label',
            field=models.CharField(max_length=64, null=True, verbose_name='Template Label'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='label',
            field=models.CharField(max_length=64, verbose_name='Template Label For Msg'),
        ),
    ]
