# Generated by Django 4.1.3 on 2022-11-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tgchat_chat_type_alter_tgmessage_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Priority'),
            preserve_default=False,
        ),
    ]
