# Generated by Django 4.1.3 on 2022-11-23 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tgtemplateparsemsg_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='replace',
            field=models.CharField(default=1, max_length=80, verbose_name='Replace Pattern'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='chat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgchat', verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
