# Generated by Django 4.1.3 on 2022-11-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tgtemplateparsemsg_replace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='id_template',
            field=models.IntegerField(default=1, verbose_name='Template ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='id_tg_msg',
            field=models.BigIntegerField(default=1, verbose_name='ID Telegram Msg'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgrawmessage',
            name='id_tg_msg',
            field=models.BigIntegerField(default=2, verbose_name='ID Telegram Msg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tgrawmessage',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
