# Generated by Django 4.1.3 on 2022-11-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tgmessage_id_tg_msg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='template_off',
            field=models.BooleanField(default=False, verbose_name='Template Off'),
        ),
    ]
