# Generated by Django 4.1.3 on 2022-11-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tgmessage_template_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgmessage',
            name='template_off',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='template_off',
            field=models.BooleanField(default=False, verbose_name='Template Off'),
        ),
    ]
