# Generated by Django 4.1.3 on 2022-11-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_tgmessage_template_off_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='template_off',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='template_on',
            field=models.BooleanField(default=True, verbose_name='Template On'),
        ),
    ]
