# Generated by Django 4.1.3 on 2022-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tgtemplateparsemsg_template_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgmessage',
            name='value_float',
            field=models.FloatField(null=True, verbose_name='ValueFloat'),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='value_int',
            field=models.IntegerField(null=True, verbose_name='ValueInt'),
        ),
        migrations.AddField(
            model_name='tgmessage',
            name='value_str',
            field=models.CharField(max_length=128, null=True, verbose_name='ValueStr'),
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='report_type',
            field=models.CharField(choices=[('Counter Uniq', 'Counter Uniq'), ('Collector Value', 'Collector Value')], default='Counter Uniq', max_length=30, verbose_name='Report'),
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='value_eq',
            field=models.CharField(default=1, max_length=80, verbose_name='ValueEq'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='value_regex',
            field=models.TextField(max_length=200, null=True, verbose_name='RegexVal'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='condition_type',
            field=models.CharField(choices=[('In', 'Include'), ('Ex', 'Exclude')], default='In', max_length=2, null=True, verbose_name='In/Exclude'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='label',
            field=models.CharField(max_length=64, verbose_name='Label For Msg'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='regex',
            field=models.TextField(max_length=200, null=True, verbose_name='RegexName'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='replace',
            field=models.CharField(max_length=80, verbose_name='ReplName'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='template_on',
            field=models.BooleanField(default=True, verbose_name='On/Off'),
        ),
    ]
