# Generated by Django 4.1.3 on 2022-11-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_tgmessage_value_float_tgmessage_value_int_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='value_regex',
            field=models.TextField(default=1, max_length=100, verbose_name='RegexVal'),
            preserve_default=False,
        ),
    ]
