# Generated by Django 4.1.3 on 2022-11-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_tgtemplateparsemsg_value_regex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='value_eq',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='ValueEq'),
        ),
        migrations.AlterField(
            model_name='tgtemplateparsemsg',
            name='value_regex',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='RegexVal'),
        ),
    ]
