# Generated by Django 4.1.3 on 2022-11-25 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_tgtemplateparsemsg_value_eq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TGInlineKeyboardButton',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=20, null=True, verbose_name='Button Text')),
                ('callback_data', models.CharField(max_length=30, null=True, verbose_name='Callback data')),
                ('id_bot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgbot', verbose_name='Bot')),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgchat', verbose_name='Chat')),
            ],
            options={
                'verbose_name': 'Command Button',
                'verbose_name_plural': 'Command Buttons',
                'db_table': 'tg_inline_keyboard_button',
            },
        ),
    ]
