# Generated by Django 4.1.3 on 2022-11-25 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tglabel_alter_tginlinekeyboardbutton_button_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tglabel',
            old_name='lable',
            new_name='label',
        ),
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='label',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='id_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tglabel', verbose_name='Label'),
            preserve_default=False,
        ),
    ]
