# Generated by Django 4.1.3 on 2022-11-25 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_lable_tglabel_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='chat_id',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='id_chat',
            field=models.ManyToManyField(to='core.tgchat', verbose_name='Chat'),
        ),
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='id_label',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='id_label',
            field=models.ManyToManyField(to='core.tglabel', verbose_name='Label'),
        ),
    ]
