# Generated by Django 4.1.3 on 2022-11-25 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_tgtemplateparsemsg_chat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tglabel',
            name='label',
            field=models.CharField(max_length=50, null=True, verbose_name='Label'),
        ),
    ]
