# Generated by Django 4.1.3 on 2022-11-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_tglabel_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='id_chat',
        ),
        migrations.RemoveField(
            model_name='tgtemplateparsemsg',
            name='id_label',
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='id_chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tgchat', verbose_name='Chat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tgtemplateparsemsg',
            name='id_label',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tglabel', verbose_name='Label'),
            preserve_default=False,
        ),
    ]
