# Generated by Django 4.1.3 on 2022-11-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_tgtemplateparsemsg_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tginlinekeyboardbutton',
            name='labels',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.tglabel', verbose_name='Label'),
            preserve_default=False,
        ),
    ]
