# Generated by Django 4.1.3 on 2022-11-27 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tginlinekeyboardbutton_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgmessage',
            name='value_int',
        ),
    ]
