# Generated by Django 4.1.3 on 2022-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_remove_tgmessage_value_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgmessage',
            name='chat_name',
            field=models.CharField(max_length=64, null=True, verbose_name='Chat'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='id_template',
            field=models.IntegerField(verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='label',
            field=models.CharField(max_length=64, null=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='message',
            field=models.CharField(max_length=128, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='value_float',
            field=models.FloatField(blank=True, null=True, verbose_name='ValueFloat'),
        ),
        migrations.AlterField(
            model_name='tgmessage',
            name='value_str',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ValueStr'),
        ),
    ]
