# Generated by Django 4.1.3 on 2022-12-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_tgmessage_chat_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgbot",
            name="bot_on",
            field=models.BooleanField(default=True, verbose_name="On/Off"),
        ),
    ]
