# Generated by Django 4.1.3 on 2022-12-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_tgbot_bot_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgtemplateparsemsg",
            name="description",
            field=models.TextField(max_length=50, null=True, verbose_name="Descript"),
        ),
    ]
