# Generated by Django 4.1.3 on 2022-12-05 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_tgtemplateparsemsg_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tgtemplateparsemsg",
            name="description",
            field=models.CharField(max_length=80, null=True, verbose_name="Descript"),
        ),
    ]
