# Generated by Django 4.1.3 on 2022-12-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_tgtemplateparsemsg_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="tgbot",
            name="admin",
            field=models.BooleanField(default=False, verbose_name="Admin"),
        ),
        migrations.AddField(
            model_name="tginlinekeyboardbutton",
            name="admin",
            field=models.BooleanField(default=False, verbose_name="Admin"),
        ),
    ]
