# Generated by Django 4.1.3 on 2022-12-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_jrtask_jruser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jrtask",
            options={"verbose_name": "Jira Task", "verbose_name_plural": "Jira Tasks"},
        ),
        migrations.AlterModelOptions(
            name="jruser",
            options={"verbose_name": "Jira User", "verbose_name_plural": "Jira Users"},
        ),
        migrations.RemoveField(
            model_name="jruser",
            name="token",
        ),
        migrations.RemoveField(
            model_name="jruser",
            name="username",
        ),
        migrations.AddField(
            model_name="jruser",
            name="atlassian_email",
            field=models.CharField(max_length=64, null=True, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="jruser",
            name="atlassian_token",
            field=models.BigIntegerField(
                default=1, primary_key=True, serialize=False, verbose_name="Access Token"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jruser",
            name="baseUrl",
            field=models.CharField(
                max_length=64, null=True, verbose_name="Atlassian Base Url"
            ),
        ),
    ]
