# Generated by Django 4.1.3 on 2022-12-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_jrtask_options_alter_jruser_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jruser",
            name="atlassian_token",
            field=models.CharField(
                max_length=64,
                primary_key=True,
                serialize=False,
                verbose_name="Access Token",
            ),
        ),
    ]
