# Generated by Django 4.1.3 on 2022-12-14 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_jruser_atlassian_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="JRParentTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="PTask ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, null=True, verbose_name="Key")),
                (
                    "project_key",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Project Key"
                    ),
                ),
                (
                    "parent_key",
                    models.CharField(max_length=64, null=True, verbose_name="Parent Key"),
                ),
                (
                    "issuetype_name",
                    models.CharField(max_length=30, null=True, verbose_name="Issue Type"),
                ),
            ],
            options={
                "verbose_name": "Jira Parent Task",
                "verbose_name_plural": "Jira Parent Tasks",
                "db_table": "jr_parent_task",
            },
        ),
        migrations.CreateModel(
            name="JRTemplateCreateTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        primary_key=True, serialize=False, verbose_name="PTask ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, null=True, verbose_name="Key")),
                (
                    "rest_api_url",
                    models.CharField(
                        max_length=64, null=True, verbose_name="Project Key"
                    ),
                ),
                (
                    "request_header",
                    models.CharField(max_length=64, null=True, verbose_name="ReqHeader"),
                ),
                (
                    "request_body",
                    models.CharField(max_length=64, null=True, verbose_name="ReqBody"),
                ),
                (
                    "id_label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.tglabel",
                        verbose_name="Label",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jira Template Create Task",
                "verbose_name_plural": "Jira Template Create Tasks",
                "db_table": "jr_template_create_task",
            },
        ),
    ]
