# Generated by Django 4.1.3 on 2022-12-14 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_jrparenttask_jrtemplatecreatetask"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jrtemplatecreatetask",
            name="key",
        ),
        migrations.RemoveField(
            model_name="jrtemplatecreatetask",
            name="rest_api_url",
        ),
        migrations.AddField(
            model_name="jrtemplatecreatetask",
            name="description",
            field=models.CharField(max_length=80, null=True, verbose_name="Descript"),
        ),
        migrations.AddField(
            model_name="jrtemplatecreatetask",
            name="id_parent_task",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="core.jrparenttask",
                verbose_name="ParentTask",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jrtemplatecreatetask",
            name="rest_func_url",
            field=models.CharField(max_length=64, null=True, verbose_name="RestFuncUrl"),
        ),
        migrations.AlterField(
            model_name="jrtemplatecreatetask",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, verbose_name="TemplCrTask ID"
            ),
        ),
    ]
