# Generated by Django 4.1.3 on 2022-12-14 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_remove_jrtemplatecreatetask_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jrparenttask",
            name="issuetype_name_child",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Issue Type Child"
            ),
        ),
        migrations.AlterField(
            model_name="jrtemplatecreatetask",
            name="request_body",
            field=models.TextField(max_length=300, null=True, verbose_name="ReqBody"),
        ),
        migrations.AlterField(
            model_name="jrtemplatecreatetask",
            name="request_header",
            field=models.TextField(max_length=100, null=True, verbose_name="ReqHeader"),
        ),
    ]
