# Generated by Django 4.1.3 on 2022-12-14 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_alter_jrparenttask_parent_key_alter_jrtask_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jrtemplatecreatetask",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
