# Generated by Django 4.1.3 on 2022-12-14 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_jrtemplatecreatetask_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jrtemplatecreatetask",
            name="request_body",
            field=models.TextField(max_length=1000, null=True, verbose_name="ReqBody"),
        ),
    ]
